repos:
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.54.3
    hooks:
      - id: swiftformat
  - repo: https://github.com/realm/SwiftLint
    rev: 0.56.1
    hooks:
      - id: swiftlint

