name: Sofia
options:
  bundleIdPrefix: id.alfian
  xcodeVersion: 14.2
packages:
  OAuthSwift:
    url: https://github.com/OAuthSwift/OAuthSwift.git
    from: 2.0.0
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: 24.0.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.0.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI.git
    from: 3.1.0
targets:
  Sofia:
    platform: iOS
    type: application
    deploymentTarget: "14.0"
    sources: [Sofia]
    configFiles:
      Debug: Sofia/Configuration/Debug.xcconfig
      Release: Sofia/Configuration/Release.xcconfig
    postBuildScripts:
      - path: swiftformat_script.sh
        name: SwiftFormat
      - path: swiftlint_script.sh
        name: SwiftLint
    settings:
      base:
        INFOPLIST_FILE: Sofia/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: "9GE8EQEDQB"
        ENABLE_BITCODE: false
    dependencies:
      - package: OAuthSwift
      - package: KeychainSwift
      - package: Alamofire
      - package: SDWebImageSwiftUI
